version: '3.4'

services:
  cinema.api:
    image: ${DOCKER_REGISTRY-}cinemaapi
    build:
      context: .
      dockerfile: Cinema.API\Dockerfile
    ports:
       - "5000:5000"
       - "5001:5001"

